"use client";

import { useEffect, useState } from "react";

const templates: Record<string, string> = {
  "Arduino C++": `#include <Arduino.h>

constexpr int STATUS_LED = 2;

void setup() {
  Serial.begin(115200);
  pinMode(STATUS_LED, OUTPUT);
}

void loop() {
  digitalWrite(STATUS_LED, !digitalRead(STATUS_LED));
  delay(500);
}`,
  Python: `print("Hello from AsV_IDE")\n\n# Start building your local project here.\n`,
  JavaScript: `console.log("Hello from AsV_IDE");\n`,
  HTML: `<!doctype html>\n<html><body><h1>Hello, AsV_IDE</h1></body></html>\n`,
  Lua: `print("Hello from AsV_IDE")\n`, Ruby: `puts "Hello from AsV_IDE"\n`,
};
const themes = ["aurora", "midnight", "neon", "sunset"];
const glyphs = "リ∆⟟꙰ꖎ⚚ᔑ╎ᓭ⍊ᒷℸ ̣ᓵᓵ∴";
const welcomeText: Record<string, { label: string; title: string; description: string }> = {
  English: { label: "LOCAL CREATOR STUDIO", title: "Welcome back.", description: "Build for ESP32, Arduino, the web, or your computer—one local workspace." },
  Arabic: { label: "استوديو الإبداع المحلي", title: "مرحباً بعودتك.", description: "أنشئ لمتحكم ESP32 وأردوينو والويب وجهازك في مساحة محلية واحدة." },
  Hindi: { label: "लोकल क्रिएटर स्टूडियो", title: "वापस आने पर स्वागत है।", description: "ESP32, Arduino, वेब या अपने कंप्यूटर के लिए एक स्थानीय कार्यक्षेत्र में बनाएं।" },
  Spanish: { label: "ESTUDIO CREADOR LOCAL", title: "Bienvenido de nuevo.", description: "Crea para ESP32, Arduino, la web o tu ordenador desde un espacio local." },
  French: { label: "ATELIER CRÉATEUR LOCAL", title: "Bon retour.", description: "Créez pour ESP32, Arduino, le web ou votre ordinateur dans un espace local." },
};
type Project = { name: string; language: string; code: string };

export default function Home() {
  const [booting, setBooting] = useState(true); const [welcome, setWelcome] = useState(true);
  const [project, setProject] = useState<Project>({ name: "blink-node", language: "Arduino C++", code: templates["Arduino C++"] });
  const [theme, setTheme] = useState("aurora"); const [active, setActive] = useState("Explorer"); const [file, setFile] = useState<"README" | "Code">("README");
  const [settingsOpen, setSettingsOpen] = useState(false); const [loginOpen, setLoginOpen] = useState(false); const [adminMode, setAdminMode] = useState(false); const [displayName, setDisplayName] = useState(""); const [notebook, setNotebook] = useState(false); const [terminal, setTerminal] = useState("Ready to work locally."); const [about, setAbout] = useState("AsV_IDE is built by makers who believe great tools should stay local, fast, and yours."); const [hiring, setHiring] = useState("Join our Discord — we are hiring developers, hardware builders, and plugin creators."); const [loaded, setLoaded] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setBooting(false), 600); try { const saved = JSON.parse(localStorage.getItem("asv-ide-workspace") || "null"); if (saved?.project) setProject(saved.project); if (saved?.theme) setTheme(saved.theme); if(saved?.about)setAbout(saved.about);if(saved?.hiring)setHiring(saved.hiring);if(saved?.adminMode)setAdminMode(true);if(saved?.displayName)setDisplayName(saved.displayName); } catch {} setLoaded(true); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (loaded) localStorage.setItem("asv-ide-workspace", JSON.stringify({ project, theme, about, hiring, adminMode, displayName })); }, [loaded, project, theme, about, hiring, adminMode, displayName]);
  useEffect(() => { const receive = (event: Event) => setTerminal((event as CustomEvent<string>).detail); window.addEventListener("asv-execute-output", receive); return () => window.removeEventListener("asv-execute-output", receive); }, []);
  const createProject = (name: string, language: string) => { const cleanName = name.trim() || "new-project"; setProject({ name: cleanName, language, code: templates[language] }); setFile("README"); setWelcome(false); setTerminal(`Created ${cleanName} locally.`); };
  const run = () => { if (project.language === "HTML") { setTerminal("HTML preview is ready in the browser."); return; } const runner = (window as Window & { asvExecutor?: { run: (language: string, code: string) => void } }).asvExecutor; if (!runner) { setTerminal("Open the macOS AsV_IDE app to run local code."); return; } if (!["Python", "JavaScript", "Lua", "Ruby"].includes(project.language)) { setTerminal("Arduino needs its board toolchain and a connected board to compile/upload."); return; } setTerminal(`Running ${project.language} locally…`); runner.run(project.language, project.code); };
  if (booting) return <main className="boot-screen"><div className="boot-mark">A<span>V</span></div><div className="boot-name">AsV_IDE</div><div className="glyph-line">{glyphs}</div><div className="boot-loader"><i /></div><p>INITIALIZING LOCAL WORKSPACE</p></main>;
  if (welcome) return <Welcome theme={theme} setTheme={setTheme} onCreate={createProject} displayName={displayName} />;
  if (notebook) return <Notebook theme={theme} onBack={() => setNotebook(false)} />;
  const nav = [["⌘", "Explorer"], ["⌕", "Search"], ["⑂", "Source Control"], ["▣", "Extensions"], ["◈", "Device"], ["ⓘ", "About Us"], ...(adminMode ? [["♛", "Admin"]] : [])];
  return <main className={`ide-shell theme-${theme}`}>
    <header className="topbar"><div className="brand"><b>A<span>V</span></b><strong>AsV_IDE</strong><em>{adminMode ? "ADMIN EDITION" : "LOCAL WORKSPACE"}</em></div><div className="project-pill"><span className="dot" />{project.name}</div><div className="top-actions"><button className="visual-button" onClick={() => setLoginOpen(true)}>{displayName ? `Hi, ${displayName}` : "Sign in"}</button><button className="visual-button" onClick={() => setNotebook(true)}>▤ Notebook</button><button className="run-button" onClick={run}>▶ Run</button><button className="avatar" onClick={() => setSettingsOpen(true)} title="Open settings">⚙</button></div></header>
    <section className="workspace"><aside className="activity-bar">{nav.map(([icon, label]) => <button key={label} onClick={() => setActive(label)} className={active === label ? "active" : ""} title={label}>{icon}</button>)}<button className="settings" onClick={() => setSettingsOpen(true)} title="Settings">⚙</button></aside><aside className="side-panel"><div className="panel-heading">{active.toUpperCase()}</div><Sidebar active={active} project={project} openReadme={() => setFile("README")} openCode={() => setFile("Code")} about={about} hiring={hiring} adminMode={adminMode}/><div className="side-bottom"><span>◉ Local-first</span><span>◉ Autosaved</span></div></aside><section className="editor-area">{active === "Admin" ? <AdminPanel about={about} setAbout={setAbout} hiring={hiring} setHiring={setHiring} /> : <><div className="editor-tabs"><button className={file === "README" ? "file-tab" : ""} onClick={() => setFile("README")}>▣ README.md</button><button className={file === "Code" ? "file-tab" : ""} onClick={() => setFile("Code")}>⌘ {project.name}</button></div><div className="crumbs">AsV_IDE / projects / {project.name} / <b>{file === "README" ? "README.md" : project.language}</b></div>{file === "README" ? <Readme project={project} openCode={() => setFile("Code")} /> : <Editor project={project} setProject={setProject} />}</>}</section><aside className="inspector"><div className="inspector-head"><span>DEVICE PULSE</span><span className="pulse">WAITING</span></div><div className="device-card"><div className="chip-art">ESP<br/><b>32</b></div><h3>No device attached</h3><p>Connect USB or Bluetooth when ready.</p><button onClick={() => setTerminal("Use Connect USB in the native app to choose a board.")}>Connect device</button></div><button className="ai-card" onClick={() => setSettingsOpen(true)}><span>✦</span><div><b>AsV Intelligence</b><small>Configure AI providers</small></div><i>→</i></button></aside></section>
    <section className="community-banner">◈ {hiring}</section><section className="terminal"><div className="terminal-bar"><div><b>TERMINAL</b><span>OUTPUT</span><span>PROBLEMS <i>0</i></span></div><button onClick={() => setTerminal("Console cleared.")}>Clear</button></div><div className="terminal-body"><p><b>›</b> {terminal}</p></div></section><footer><div><span>↻</span> Saved locally</div><div>{project.language} · UTF-8 · AsV_IDE</div></footer>{settingsOpen && <Settings theme={theme} setTheme={setTheme} onClose={() => setSettingsOpen(false)} />}{loginOpen && <Login onClose={() => setLoginOpen(false)} onAdmin={(name) => { setAdminMode(true); setDisplayName(name); setActive("Admin"); setLoginOpen(false); setTerminal(`Welcome ${name} — edit your workspace panels below.`); }}/>} 
  </main>;
}

function Welcome({ theme, setTheme, onCreate, displayName }: { theme: string; setTheme: (theme: string) => void; onCreate: (name: string, language: string) => void; displayName: string }) {
  const [name, setName] = useState(""); const [language, setLanguage] = useState("Arduino C++"); const [languageName, setLanguageName] = useState("English");
  const copy = welcomeText[languageName];
  const title = displayName ? `${copy.title.replace(".", "")}, ${displayName}.` : copy.title;
  return <main className={`welcome-screen public-welcome theme-${theme}`}><div className="welcome-glow"/><nav className="public-nav"><strong>AsV_IDE</strong><span>LOCAL MAKER STUDIO</span><a href="https://github.com/mistfans24-maker/AsV_IDE" target="_blank" rel="noreferrer">View on GitHub ↗</a></nav><section className="public-hero"><div className="public-copy"><span className="eyebrow">{copy.label}</span><h1>{title}</h1><p>{copy.description}</p><div className="language-picker"><span>LANGUAGE</span>{Object.keys(welcomeText).map(item => <button key={item} onClick={() => setLanguageName(item)} className={languageName === item ? "selected" : ""}>{item}</button>)}</div><div className="theme-picker"><span>BACKGROUND</span>{themes.map(item => <button key={item} onClick={() => setTheme(item)} className={theme === item ? "selected" : ""}>{item}</button>)}</div><div className="new-project welcome-create"><h2>Create a new project</h2><input value={name} onChange={event => setName(event.target.value)} placeholder="Project name"/><div className="language-grid">{Object.keys(templates).map(item => <button key={item} onClick={() => setLanguage(item)} className={language === item ? "selected" : ""}>{item}</button>)}</div><button className="primary" onClick={() => onCreate(name, language)}>Start building →</button></div></div><aside className="public-device"><div className="device-orbit"><i/><b>ESP<br/>32</b></div><span>DEVICE-READY WORKSPACE</span><h2>From first blink to real build.</h2><p>Create code, learn hardware, and keep every experiment on your own computer.</p><div className="signal-row"><b>● Local-first</b><b>● Multi-language</b><b>● Plugin-ready</b></div></aside></section><section className="public-features"><article><span>01</span><h2>Project Compass</h2><p>Every project opens with a human README: what to build next, what to connect, and where to experiment.</p></article><article><span>02</span><h2>Code + Canvas</h2><p>Move from syntax-coloured code to visual notebook thinking without leaving your workspace.</p></article><article><span>03</span><h2>Learning Mode</h2><p>Start small, run locally, then grow into ESP32, web, Python, Lua, Ruby, or JavaScript projects.</p></article></section><footer className="welcome-footer">BUILT FOR CURIOUS MAKERS · LOCAL-FIRST · OPEN TO CONTRIBUTORS</footer></main>;
}

function Sidebar({ active, project, openReadme, openCode, about, hiring, adminMode }: { active: string; project: Project; openReadme: () => void; openCode: () => void; about: string; hiring: string; adminMode: boolean }) { if (active === "Explorer") return <><div className="tree-title">▾ {project.name.toUpperCase()} <button>＋</button></div><button className="tree-file" onClick={openCode}>⌘ &nbsp; {project.name}</button><button className="tree-file" onClick={openReadme}>▣ &nbsp; README.md</button><div className="tree-title closed">› LIBRARIES</div><div className="tree-title closed">› EXAMPLES</div></>; if (active === "Search") return <div className="sidebar-message"><b>Search this project</b><input placeholder="Search files"/><small>Search is ready for your project files.</small></div>; if (active === "Source Control") return <div className="sidebar-message"><b>Source Control</b><small>Changes are autosaved locally. GitHub connection is ready for OAuth setup.</small></div>; if (active === "Extensions") return <div className="sidebar-message"><b>Extensions</b><button>✦ Gemini Assist</button><button>◉ Serial Studio</button><small>Extensions can be added without changing your project.</small></div>; if (active === "About Us") return <div className="sidebar-message about-panel"><b>About AsV_IDE</b><small>{about}</small><strong>Lead developer & founder</strong><small>AsV — maker, builder, and the person turning an idea into a local-first IDE.</small><div className="discord-note">{hiring}</div></div>; if (active === "Admin" && adminMode) return <div className="sidebar-message"><b>Admin mode active</b><small>You can edit the About and hiring panels from the Admin workspace.</small></div>; return <div className="sidebar-message"><b>Device Center</b><small>Attach an ESP32 by USB or Bluetooth to flash and view serial data.</small><button>Connect a board</button></div>; }
function Readme({ project, openCode }: { project: Project; openCode: () => void }) { return <article className="readme"><span className="eyebrow">WELCOME TO YOUR PROJECT</span><h1>Welcome to {project.name}.</h1><p>This local {project.language} project is ready to become anything you want: an ESP32 firmware build, automation tool, web dashboard, or experiment.</p><h2>Start making</h2><ol><li>Open the main code file and write your first feature.</li><li>Use <b>Run</b> to execute supported local languages, or connect an ESP32 for board work.</li><li>Keep notes here, add files in Explorer, and save everything locally.</li></ol><button className="primary readme-action" onClick={openCode}>Open {project.name} →</button></article>; }
function Editor({ project, setProject }: { project: Project; setProject: (project: Project) => void }) { return <div className="editor-wrap"><ol className="line-numbers">{Array.from({ length: Math.max(16, project.code.split("\n").length) }, (_, index) => <li key={index}>{index + 1}</li>)}</ol><textarea aria-label="Code editor" spellCheck="false" value={project.code} onChange={event => setProject({ ...project, code: event.target.value })}/></div>; }
function Login({ onClose, onAdmin }: { onClose: () => void; onAdmin: (name: string) => void }) { const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("Choose a provider or connect an Admin server."); const submit = () => { setMessage("Admin sign-in is disabled until a server-side authentication provider is configured. Passwords are never stored in this app."); }; return <div className="modal-back"><section className="modal login-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">ACCOUNT</span><h2>Sign in to AsV_IDE</h2><p>Your display name appears in the welcome screen after a connected provider returns it.</p><div className="login-providers"><section><b>Google</b><small>Continue with Google after OAuth is configured.</small><button onClick={() => setMessage("Google sign-in needs your OAuth client ID before it can be connected.")}>Continue with Google</button></section><section><b>GitHub</b><small>Connect a GitHub account for repository sync.</small><button onClick={() => setMessage("GitHub sign-in needs your OAuth client ID before it can be connected.")}>Continue with GitHub</button></section></div><div className="admin-login"><b>Admin access</b><input value={username} onChange={event => setUsername(event.target.value)} placeholder="Username"/><input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Password"/><button className="primary" onClick={submit}>Sign in securely</button><small>{message}</small></div></section></div>; }
function AdminPanel({ about, setAbout, hiring, setHiring }: { about: string; setAbout: (value: string) => void; hiring: string; setHiring: (value: string) => void }) { return <article className="admin-panel"><span className="eyebrow">ADMIN WORKSPACE</span><h1>Welcome Admin.</h1><p>Edit the live community panels below. Your changes save locally and appear immediately in the sidebar and banner.</p><label>About AsV_IDE<textarea value={about} onChange={event => setAbout(event.target.value)} /></label><label>Discord / hiring banner<textarea value={hiring} onChange={event => setHiring(event.target.value)} /></label><div className="admin-status">● Changes saved locally</div></article>; }
function Settings({ theme, setTheme, onClose }: { theme: string; setTheme: (theme: string) => void; onClose: () => void }) { const [spotify, setSpotify] = useState(false); const [playing, setPlaying] = useState(false); return <div className="modal-back"><section className="modal settings-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">WORKSPACE SETTINGS</span><h2>Make AsV_IDE yours.</h2><p>Changes save locally and apply across the editor, welcome screen, and notebook.</p><h3>Theme</h3><div className="visual-grid">{themes.map(item => <button key={item} onClick={() => setTheme(item)} className={`visual-swatch ${item} ${theme === item ? "selected" : ""}`}><i/><b>{item}</b></button>)}</div><h3>Spotify</h3>{spotify ? <div className="spotify-player"><div><span className="spotify-dot">●</span><b>Spotify embedded player</b><small>Log in inside Spotify to use your account.</small></div><div className="music-controls"><button onClick={() => setPlaying(!playing)}>{playing ? "❚❚ Pause" : "▶ Play"}</button><button>↶</button><button>↷</button></div><iframe title="Spotify player" src="https://open.spotify.com/embed/playlist/37i9dQZF1DX4JAvHpjipBk?utm_source=generator" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"/></div> : <div className="spotify-connect"><b>Listen while you build.</b><small>Connect opens Spotify’s secure login in the embedded player.</small><button className="primary" onClick={() => setSpotify(true)}>Connect Spotify</button></div>}<h3>AI providers</h3><div className="settings-row"><span>OpenAI, Gemini, Claude, and local Ollama</span><button>Manage keys</button></div></section></div>; }
function Notebook({ theme, onBack }: { theme: string; onBack: () => void }) { const [code, setCode] = useState("print('Hello, AsV!')"); return <main className={`notebook theme-${theme}`}><header className="notebook-top"><div className="brand"><b>A<span>V</span></b><strong>AsV_IDE</strong><em>NOTEBOOK</em></div><button className="visual-button" onClick={onBack}>← IDE</button></header><section className="notebook-sheet"><div className="notebook-title"><span>LOCAL NOTEBOOK</span><h1>Untitled project</h1><p>Your selected workspace theme applies here too.</p></div><article className="note-cell"><div className="markdown"><b>Welcome to AsV Notebook</b><p>Write, run, and keep project notes alongside your code.</p></div></article><article className="note-cell code-cell"><div className="cell-head"><span>⌘ CODE CELL</span><button>▶</button></div><textarea value={code} onChange={event => setCode(event.target.value)} /></article></section></main>; }
